# Generated by Django 5.2.11 on 2026-03-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('matricule_fiscal', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=2)),
                ('adresse', models.CharField(max_length=300)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_creation', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
