# Generated by Django 5.2.12 on 2026-05-09 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvoirFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée')], default='brouillon', max_length=20)),
                ('mf_fournisseur', models.CharField(blank=True, max_length=30)),
                ('adresse_fournisseur', models.CharField(blank=True, max_length=200)),
                ('telephone_fournisseur', models.CharField(blank=True, max_length=30)),
                ('email_fournisseur', models.CharField(blank=True, max_length=100)),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_rem', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('base_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fournisseurs.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='BonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée')], default='brouillon', max_length=20)),
                ('mf_fournisseur', models.CharField(blank=True, max_length=30)),
                ('adresse_fournisseur', models.CharField(blank=True, max_length=200)),
                ('telephone_fournisseur', models.CharField(blank=True, max_length=30)),
                ('email_fournisseur', models.CharField(blank=True, max_length=100)),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_rem', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('base_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fournisseurs.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='brouillon', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_rem', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('base_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('mf_fournisseur', models.CharField(blank=True, max_length=50)),
                ('adresse_fournisseur', models.CharField(blank=True, max_length=255)),
                ('telephone_fournisseur', models.CharField(blank=True, max_length=20)),
                ('email_fournisseur', models.EmailField(blank=True, max_length=254)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fournisseurs.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='FactureAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('payee', 'Payée')], default='brouillon', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_rem', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('base_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('mf_fournisseur', models.CharField(blank=True, max_length=50)),
                ('adresse_fournisseur', models.CharField(blank=True, max_length=255)),
                ('telephone_fournisseur', models.CharField(blank=True, max_length=20)),
                ('email_fournisseur', models.EmailField(blank=True, max_length=254)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fournisseurs.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='LigneAvoirFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10)),
                ('prix_ht', models.DecimalField(decimal_places=3, max_digits=10)),
                ('taux_rem', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('avoir_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.avoirfournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10)),
                ('prix_ht', models.DecimalField(decimal_places=3, max_digits=10)),
                ('taux_rem', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('bon_reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.bonreception')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_ht', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix Achat')),
                ('taux_rem', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.demande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFactureAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_ht', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix Achat')),
                ('taux_rem', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.factureachat')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
            ],
        ),
    ]
