# Generated by Django 5.2.12 on 2026-05-09 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvoirClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mf_client', models.CharField(blank=True, max_length=30)),
                ('adresse_client', models.CharField(blank=True, max_length=200)),
                ('telephone_client', models.CharField(blank=True, max_length=30)),
                ('email_client', models.CharField(blank=True, max_length=100)),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_rem', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('base_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='brouillon', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_rem', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('base_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('mf_client', models.CharField(blank=True, max_length=50)),
                ('adresse_client', models.CharField(blank=True, max_length=255)),
                ('telephone_client', models.CharField(blank=True, max_length=20)),
                ('email_client', models.EmailField(blank=True, max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('payee', 'Payée')], default='brouillon', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_rem', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('base_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('mf_client', models.CharField(blank=True, max_length=50)),
                ('adresse_client', models.CharField(blank=True, max_length=255)),
                ('telephone_client', models.CharField(blank=True, max_length=20)),
                ('email_client', models.EmailField(blank=True, max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mf_client', models.CharField(blank=True, max_length=30)),
                ('adresse_client', models.CharField(blank=True, max_length=200)),
                ('telephone_client', models.CharField(blank=True, max_length=30)),
                ('email_client', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée')], default='brouillon', max_length=20)),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_rem', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('base_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.facture')),
            ],
        ),
        migrations.CreateModel(
            name='LigneAvoirClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10)),
                ('prix_ht', models.DecimalField(decimal_places=3, max_digits=10)),
                ('taux_rem', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('avoir_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.avoirclient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10)),
                ('prix_ht', models.DecimalField(decimal_places=3, max_digits=10)),
                ('taux_rem', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('bon_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.bonlivraison')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_rem', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_ht', models.DecimalField(decimal_places=3, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.devis')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_rem', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_ht', models.DecimalField(decimal_places=3, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
            ],
        ),
    ]
