# Generated by Django 5.2.11 on 2026-03-10 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbcBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MessageSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_entity_in', models.CharField(max_length=100)),
                ('transmitting_country', models.CharField(max_length=2)),
                ('receiving_country', models.CharField(max_length=2)),
                ('message_type', models.CharField(max_length=50)),
                ('message_ref_id', models.CharField(max_length=100)),
                ('reporting_period', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CbcReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('cbc_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbc.cbcbody')),
            ],
        ),
        migrations.AddField(
            model_name='cbcbody',
            name='message_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbc.messagespec'),
        ),
        migrations.CreateModel(
            name='ReportingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('reporting_role', models.CharField(max_length=50)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.societe')),
            ],
        ),
        migrations.AddField(
            model_name='cbcbody',
            name='reporting_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbc.reportingentity'),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenues', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax_paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('employees', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbc.cbcreport')),
            ],
        ),
    ]
