# Generated by Django 5.2.12 on 2026-05-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CbcBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MessageSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_entity_in', models.CharField(max_length=100)),
                ('transmitting_country', models.CharField(default='TN', max_length=2)),
                ('receiving_country', models.CharField(default='TN', max_length=2)),
                ('message_type', models.CharField(default='CBC', max_length=10)),
                ('message_ref_id', models.CharField(max_length=200)),
                ('reporting_period', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tin', models.CharField(max_length=50)),
                ('country_code', models.CharField(default='TN', max_length=2)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CbcReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('unrelated_revenue', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('related_revenue', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('total_revenue', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('profit_loss', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('tax_paid', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('tax_accrued', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('capital', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('earnings', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('employees', models.IntegerField(default=0)),
                ('assets', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('cbc_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbc.cbcbody')),
            ],
        ),
        migrations.AddField(
            model_name='cbcbody',
            name='message_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbc.messagespec'),
        ),
        migrations.AddField(
            model_name='cbcbody',
            name='reporting_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbc.reportingentity'),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=2)),
                ('activity', models.CharField(max_length=200)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbc.cbcreport')),
            ],
        ),
    ]
