# Generated by Django 5.2.11 on 2026-03-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportingentity',
            old_name='reporting_role',
            new_name='tin',
        ),
        migrations.RemoveField(
            model_name='reportingentity',
            name='societe',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='profit_loss',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='revenues',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='tax_paid',
        ),
        migrations.AddField(
            model_name='cbcreport',
            name='assets',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cbcreport',
            name='capital',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cbcreport',
            name='earnings',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cbcreport',
            name='employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cbcreport',
            name='profit_loss',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cbcreport',
            name='related_revenue',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cbcreport',
            name='tax_accrued',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cbcreport',
            name='tax_paid',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cbcreport',
            name='total_revenue',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cbcreport',
            name='unrelated_revenue',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='reportingentity',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='reportingentity',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reportingentity',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='summary',
            name='activity',
            field=models.CharField(default='commerce', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='country_code',
            field=models.CharField(default='commerce', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='entity_name',
            field=models.CharField(default='commerce', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagespec',
            name='message_ref_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='messagespec',
            name='message_type',
            field=models.CharField(default='CBC', max_length=10),
        ),
        migrations.AlterField(
            model_name='messagespec',
            name='receiving_country',
            field=models.CharField(default='TN', max_length=2),
        ),
        migrations.AlterField(
            model_name='messagespec',
            name='reporting_period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='messagespec',
            name='transmitting_country',
            field=models.CharField(default='TN', max_length=2),
        ),
        migrations.AlterField(
            model_name='reportingentity',
            name='country_code',
            field=models.CharField(default='TN', max_length=2),
        ),
    ]
