# Generated by Django 5.2.11 on 2026-03-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0002_rename_reporting_role_reportingentity_tin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingentity',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
