# Generated by Django 5.2.12 on 2026-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='solde_initial',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
    ]
