# Generated by Django 5.2.12 on 2026-04-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='solde_initial',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
    ]
