# Generated by Django 5.2.12 on 2026-05-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='type_contribuable',
            field=models.CharField(choices=[('PP', 'Personne Physique'), ('PM', 'Personne Morale')], default='PM', max_length=2),
        ),
    ]
