# Generated by Django 5.2.12 on 2026-05-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('type_compte', models.CharField(choices=[('CAISSE', 'Caisse'), ('BANQUE', 'Banque')], max_length=10, verbose_name='Type')),
                ('solde_initial', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Solde initial')),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
