# Generated by Django 5.2.12 on 2026-05-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('comptes', '0001_initial'),
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('observation', models.TextField(blank=True)),
                ('origine', models.CharField(blank=True, max_length=50)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='comptes.compte')),
            ],
        ),
        migrations.CreateModel(
            name='ReglementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=3, max_digits=12)),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
                ('mode_paiement', models.CharField(blank=True, choices=[('Espece', 'Espèce'), ('Cheque', 'Cheque'), ('Virement', 'Virement'), ('Lettre de change', 'Lettre de change')], max_length=50)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptes.compte', verbose_name='0.1- comptes')),
            ],
        ),
        migrations.CreateModel(
            name='ReglementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=3, max_digits=12)),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
                ('mode_paiement', models.CharField(blank=True, choices=[('Espece', 'Espèce'), ('Cheque', 'Cheque'), ('Virement', 'Virement'), ('Lettre de change', 'Lettre de change')], max_length=50)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptes.compte', verbose_name='0.1- comptes')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur')),
            ],
        ),
    ]
