# Generated by Django 5.2.12 on 2026-05-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglementclient',
            name='echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reglementfournisseur',
            name='echeance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
