# Generated by Django 5.2.12 on 2026-05-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('p_achat', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Prix Achat')),
                ('prix_ht', models.DecimalField(decimal_places=3, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19, max_digits=4)),
                ('stock_initial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seuil', models.IntegerField(default=0)),
                ('date_creation', models.DateField()),
            ],
        ),
    ]
